### ISSUE TITLE
Github Project

### ISSUE THREAD

**Issue by rudicarrilloypr** [rudicarrilloypr/kanban-capstone-js-module2#21]
[Link to Project](https://github.com/rudicarrilloypr/kanban-capstone-js-module2/projects/1)

**Comment by rudicarrilloypr** [comment]
we are 2 partners:

- Rodolfo Carrillo @rudicarrilloypr 
- Joseph Lwanzo @Grandi0z

**Comment by algerina** [comment]
Hi Team,

Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉

Highlights
✅ Correct set of project kanban
✅ Neat Project cards

Cheers and Happy coding!👏👏👏
